<a href="https://colab.research.google.com/github/hritikarautela-ops/DA108/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

In [32]:
import time

size = 100000
p_list = list(range(size))
n_array = np.arange(size)

# Timing list operation
start = time.time()
p_list = [x + 2 for x in p_list]
print(f"Python List time: {time.time() - start:.4f}s")

# Timing Numpy array operation
start = time.time()
n_array = n_array + 2
print(f"Numpy array time: {time.time() - start:.4f}s")


Python List time: 0.0161s
Numpy array time: 0.0006s


In [33]:
# Inspecting 2D array
x = np.array([[1, 2, 3], [4, 5, 6]])
print("Array x\n", x)
print("Shape of Array:", x.shape)
print("Dimention of Array:", x.ndim)

Array x
 [[1 2 3]
 [4 5 6]]
Shape of Array: (2, 3)
Dimention of Array: 2


In [34]:
arr = np.arange(10, 26).reshape(4,4)
print(arr)
print("Print 2nd column:\n", arr[:, 1])
print("Print last 3 rows:\n", arr[1:,:])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
Print 2nd column:
 [11 15 19 23]
Print last 3 rows:
 [[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [35]:
scores = np.array([85, 92, 58, 77, 89, 42])
marks = scores >= 80
print("The Marks:", marks)
print(scores[scores >= 80])
passing_marks = scores[marks]
print("Highest_Marks:", passing_marks)
# mid_range
mid_range =  scores[(scores >= 60) & (scores <= 80)]
print("Mid_Range_Marks:", mid_range)

The Marks: [ True  True False False  True False]
[85 92 89]
Highest_Marks: [85 92 89]
Mid_Range_Marks: [77]


In [36]:
data = np.array([[1, 1, 1],
                 [5, 5, 5]])
print("Sum of elements vertically:", data.sum(axis=0))
print("Sum of elements horizontally:", data.sum(axis=1))

Sum of elements vertically: [6 6 6]
Sum of elements horizontally: [ 3 15]


## **Mini Project**

### Rotten Numpy Critic

In [55]:
# Rating Movies (1.0 to 5.0)
movies = ['Avengers', 'Barbie', 'Joker', 'Intersteller', 'Parasite', 'Spiderman']
# Create a random Rating from 1.0 to 5.0 for Movies mentioned above
# Number of critics = 12
# size of Rating Grid = 12 x 6
np.random.seed(42) # Ensure rating creates same numbers for every new run of code
ratings = np.random.uniform(1.0, 5.0, size=(12, 6)).round(1)
print(ratings)
# Sum of Each Movie rating
print("Sum of Each Movie ratings:\n", ratings.sum(axis=0))
print("Average score of 'Barbie' Movie :", ratings.mean(axis=0)[1])

[[2.5 4.8 3.9 3.4 1.6 1.6]
 [1.2 4.5 3.4 3.8 1.1 4.9]
 [4.3 1.8 1.7 1.7 2.2 3.1]
 [2.7 2.2 3.4 1.6 2.2 2.5]
 [2.8 4.1 1.8 3.1 3.4 1.2]
 [3.4 1.7 1.3 4.8 4.9 4.2]
 [2.2 1.4 3.7 2.8 1.5 3. ]
 [1.1 4.6 2.  3.7 2.2 3.1]
 [3.2 1.7 4.9 4.1 4.8 4.6]
 [3.4 4.7 1.4 1.8 1.2 2.3]
 [2.6 2.1 4.3 2.4 2.1 3.2]
 [1.6 4.2 1.3 4.9 4.1 1.8]]
Sum of Each Movie ratings:
 [31.  37.8 33.1 38.1 31.3 35.5]
Average score of 'Barbie' Movie : 3.15


In [38]:
# Average Rating per Movie
movie_stats = ratings.mean(axis=0)
print("Average Ratings:")
for name, score in zip(movies, movie_stats):
  print(f"{name}: {score:.2f}")

# Who is the toughest critic
critic_stats = ratings.mean(axis=1)
print("Harshest critic score:", (critic_stats.min()).round(2))
print("Most generous critic score:", (critic_stats.max()).round(2))

Average Ratings:
Avengers: 2.58
Barbie: 3.15
Joker: 2.76
Intersteller: 3.18
Parasite: 2.61
Spiderman: 2.96
Harshest critic score: 2.43
Most generous critic score: 3.88


In [42]:
# Select critic index no. 6 and add .5 rating to 6 th row
boosted_ratings = ratings.copy()
boosted_ratings[6, :] = boosted_ratings[6, :] + 0.5
# Clip to ensure noone give rating more than 5
boosted_ratings = np.clip(boosted_ratings, 1.0, 5.0)
print("Updated Ratings for critic index:6 (Critic 7):\n")
print(boosted_ratings[6, :])


Updated Ratings for critic 6:

[2.7 1.9 4.2 3.3 2.  3.5]


In [43]:
# Best review list(Rating above 4.5)
masterpiece_watch = ratings > 4.5
print("Total 5-star 'Masterpiece' reviews:", np.sum(masterpiece_watch))
print("High-rating scores:", ratings[masterpiece_watch])

Total 5-star 'Masterpiece' reviews: 10
High-rating scores: [4.8 4.9 4.8 4.9 4.6 4.9 4.8 4.6 4.7 4.9]


Converting scale to 100 of first 3 rows

In [46]:
# Vectorized multoplication
new_scale = ratings * 20
print("First 3 rows ratings converted into 100 point scale:\n", new_scale[:3])

First 3 rows ratings converted into 100 point scale:
 [[50. 96. 78. 68. 32. 32.]
 [24. 90. 68. 76. 22. 98.]
 [86. 36. 34. 34. 44. 62.]]
